# Generated by Django 3.2.16 on 2024-01-18 19:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240119_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
