# Generated by Django 3.2.16 on 2024-02-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_activitylog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='created_at',
        ),
    ]
