# Generated by Django 3.2.16 on 2024-02-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_activitylog_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
